import { isConnected, requestAccess, signTransaction } from '@stellar/freighter-api';
import { Client, networks, PlayerStats } from 'soroban_militia_client';

const RPC_URL = import.meta.env.VITE_STELLAR_RPC_URL || 'https://soroban-testnet.stellar.org';
const NETWORK_PASSPHRASE = import.meta.env.VITE_STELLAR_PASSPHRASE || networks.testnet.networkPassphrase;
const CONTRACT_ID = import.meta.env.VITE_CONTRACT_ID || networks.testnet.contractId;

export function useBlockchainStats() {
  
  // Initialize the strongly typed auto-generated client
  const client = new Client({
    networkPassphrase: NETWORK_PASSPHRASE,
    contractId: CONTRACT_ID,
    rpcUrl: RPC_URL,
    allowHttp: RPC_URL.includes('localhost')
  });

  const getFreighterSigner = () => {
    return async (xdr: string, opts: any) => {
      const signed = await signTransaction(xdr, {
        network: 'TESTNET',
        networkPassphrase: opts.networkPassphrase
      });
      if (!signed) throw new Error("Transaction signing rejected or failed.");
      return signed;
    };
  };

  const getAddress = async () => {
    const connection = await isConnected();
    if (!connection.isConnected) throw new Error('Freighter not connected');

    const { address } = await requestAccess();
    if (!address) throw new Error('No address found');
    return address;
  };

  return {
    recordKill: async (playerAddress: string) => {
      try {
        console.log(`[Bindings] Recording kill for ${playerAddress}...`);
        const tx = await client.record_kill({ player: playerAddress }, { fee: 10000 });
        const result = await tx.signAndSend({ signTransaction: getFreighterSigner() });
        return result.hash;
      } catch (error) {
        console.error(`[Bindings] Error in record_kill:`, error);
        throw error;
      }
    },

    recordWin: async (playerAddress: string) => {
      try {
        console.log(`[Bindings] Recording win for ${playerAddress}...`);
        const tx = await client.record_win({ player: playerAddress }, { fee: 10000 });
        const result = await tx.signAndSend({ signTransaction: getFreighterSigner() });
        return result.hash;
      } catch (error) {
        console.error(`[Bindings] Error in record_win:`, error);
        throw error;
      }
    },

    setUsername: async (username: string) => {
      try {
        const address = await getAddress();
        console.log(`[Bindings] Setting username '${username}' for ${address}...`);
        const tx = await client.set_username({ player: address, username }, { fee: 10000 });
        const result = await tx.signAndSend({ publicKey: address, signTransaction: getFreighterSigner() });
        return result.hash;
      } catch (error) {
        console.error(`[Bindings] Error in setUsername:`, error);
        throw error;
      }
    },

    getStats: async (playerAddress: string): Promise<PlayerStats | null> => {
      try {
        if (!CONTRACT_ID) return null;
        console.log(`[Bindings] Fetching stats for ${playerAddress}...`);
        
        // This simulates the contract call and automatically parses the PlayerStats return type
        const { result } = await client.get_stats({ player: playerAddress });
        
        // The return type is strongly typed to the PlayerStats interface generated by bindings!
        return result; 
      } catch (e) {
        console.error('[Bindings] Error fetching stats:', e);
      }
      return null;
    },

    syncStats: async (kills: number, wins: number, username?: string) => {
      try {
        const address = await getAddress();
        if (address) {
          // Off-chain API sync for quick leaderboard updates
          try {
            await fetch('/api/sync-stats', {
              method: 'POST',
              body: JSON.stringify({ address, kills, wins, username }),
              headers: { 'Content-Type': 'application/json' }
            });
          } catch (e) {
            console.error('[Sync] Failed to hit API:', e);
          }

          // On-chain Win Record (Requires User Signature)
          if (wins > 0) {
             const tx = await client.record_win({ player: address }, { fee: 10000 });
             return await tx.signAndSend({ signTransaction: getFreighterSigner() });
          }
        }
      } catch (e) {
         console.warn('[Sync] On-chain sync bypassed or failed', e);
      }
    }
  };
}

